### ISSUE TITLE
No such module: atom_renderer_v8_util

### ISSUE THREAD

**Issue by snoblenet** [s-a/iron-node#130]
I've installed Iron-node with homebrew to use with a Mocha test harness.

I've set Iron-node to pause on exceptions.

I run `iron-node ./node_modules/.bin/mocha --timeout 10000`.

I see a `No such module: atom_renderer_v8_util` exception.

When I click continue I eventually get to:

```
Error: ENOENT: no such file or directory, stat '/Users/steven/Library/Application Support/iron-node/node_modules'
    at fs.existsSync (fs.js:247:13)
    at Object.fs.existsSync (ELECTRON_ASAR.js:379:16)
    at boot (file:///usr/local/lib/node_modules/iron-node/app/app.js:193:10)
    at file:///usr/local/lib/node_modules/iron-node/app/app.js:276:1
```
...then...
```
Error: No such module: atom_renderer_shell
    at process.atomBinding (/Users/steven/.nvm/versions/node/v7.10.0/lib/node_modules/iron-node/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/atom-binding-setup.js:4:14)
    at Object.<anonymous> (/Users/steven/.nvm/versions/node/v7.10.0/lib/node_modules/iron-node/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/api/shell.js:1:181)
    at Object.<anonymous> (/Users/steven/.nvm/versions/node/v7.10.0/lib/node_modules/iron-node/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/api/shell.js:3:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

And indeed there is no `node_modules` directory in Application Support, though there is an `iron-node-app` directory.

I have Atom installed on my computer but Vim is my primary editor. I have Electron installed on my computer but it's probably a very old version as I haven't used it for ages.

When I try to install `atom_renderer_v8_util`, I get:

```
$ npm install atom_renderer_v8_util -g
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/steven/.nvm/versions/node/v7.10.0/bin/node" "/Users/steven/.nvm/versions/node/v7.10.0/bin/npm" "install" "atom_renderer_v8_util" "-g"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! Cannot read property 'path' of null
```

What should I do? Thanks.

![image](https://cloud.githubusercontent.com/assets/62277/25769373/da32ff6e-325a-11e7-9489-3b894d040a2e.png)

**Comment by notetiene** [comment]
I can confirm it is not confined only to OS X. I've got v.3.0.18 on Ubuntu 16.04 and it gives me the same errors.

**Comment by s-a** [comment]
Have someone tried to update to latest electron runtime ? https://github.com/s-a/iron-node/blob/master/package.json#L47. Maybe this resolves the issue.

**Comment by notetiene** [comment]
Well, I think the issue has to do with _pause on caught exceptions_. I don't remember if it was a fatal error.

**Comment by s-a** [comment]
I recently upgraded electron dependency version. Any news about your issue with latest iron-node version?

**Comment by snoblenet** [comment]
I'm afraid I moved on to using DevTools in Chrome

**Comment by s-a** [comment]
oh OK :) Maybe we could close the issues in this tracker. It seems not many users have the same problems. I am sorry that I can not give OS X support. The best place for such special questions is https://stackoverflow.com/questions/tagged/iron-node

**Comment by akerdi** [comment]
I met this several days ago, and resolve it by closing my Shadowsocks.
