### ISSUE TITLE
--compile fails to compile sqlite3

### ISSUE THREAD

**Issue by s-a** [s-a/iron-node#42]
ref: #38 

``` bash
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Stephan\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.30.3" "--arch=ia32" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd c:\git\electron-recompile\tmp\sqlite3@3.0.10
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
```

**Comment by s-a** [comment]
history since https://github.com/s-a/electron-recompile 1.0.12
