### ISSUE TITLE
Unable to debug loopback application

### ISSUE THREAD

**Issue by pragyandas** [s-a/iron-node#99]
Whenever I try to debug a loopback application with iron-node I get the following error:

```
Error: Cannot resolve path "loopback/server/middleware/urlNotFound"
    at resolveAppPath (<Application-Path>\node_modules\loopback-boot\lib\compiler.js:355:15)
    at resolveAppScriptPath (<Application-Path>\node_modules\loopback-boot\lib\compiler.js:680:22)
    at resolveMiddlewarePath (<Application-Path>\node_modules\loopback-boot\lib\compiler.js:586:29)
    at <Application-Path>\node_modules\loopback-boot\lib\compiler.js:474:24
    at Array.forEach (native)
    at <Application-Path>\node_modules\loopback-boot\lib\compiler.js:473:18
    at Array.forEach (native)
    at <Application-Path>\node_modules\loopback-boot\lib\compiler.js:468:30
    at Array.forEach (native)
    at buildMiddlewareInstructions (<Application-Path>\node_modules\loopback-boot\lib\compiler.js:466:15)

```

P.S. Application Path is the root directory path to the solution folder.

**Comment by s-a** [comment]
dublicate of #96 can you open an issue at the createors of loopback to support the electron environment?

**Comment by pragyandas** [comment]
But I am able to debug the same code base using Visual Studio Code which is also based on electron.

**Comment by s-a** [comment]
Hmm, I do not know loopback. Difficult for me to figure out what s the reason for this issue :/
